version: "3.3"

services:
  chirpstack:
    image: chirpstack/chirpstack:4.0.0-test.7
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      resources:
        limits:
          cpus: '0.50'
          memory: 50M


    command: -c /etc/chirpstack
    restart: always
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ./lorawan-devices:/opt/lorawan-devices
    links:
      - redis
      - postgres
      - mosquitto

    depends_on:
      - postgres
      - mosquitto
      - redis
    ports:
      - 8080:8080
    secrets:
      - my_secret
    labels:
      kompose.volume.type: configMap
  chirpstack-gateway-bridge-eu868:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1700:1700
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto
    labels:
      kompose.volume.type: configMap

  chirpstack-gateway-bridge-as923:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1701:1701
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
    volumes:
      - ./configuration/chirpstack-gateway-bridge-as923:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto
    labels:
      kompose.volume.type: configMap

  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    labels:
      kompose.volume.type: hostPath

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    labels:
      kompose.volume.type: persistentVolumeClaim
    


  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    volumes: 
      - ./configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    labels:
      kompose.volume.type: configMap

volumes:
  postgresqldata:
  redisdata:
secrets:
  my_secret:
    file: configuration/secrets/my_secrets.txt